"""empty message

Revision ID: b008040d4f30
Revises: 
Create Date: 2018-04-22 00:54:17.956610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b008040d4f30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('config_name', sa.String(length=64), nullable=False),
    sa.Column('any_member_may_create_orgs', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('config_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
