"""empty message

Revision ID: bad8fa84fb9e
Revises: 
Create Date: 2018-04-28 11:06:20.722384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad8fa84fb9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fqdn', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('any_member_may_create_orgs', sa.Boolean(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server'], ['server.id'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.drop_table('configuration')
    op.drop_table('server')
    # ### end Alembic commands ###
